// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9wAaI9rY92kIOrCV-b4EdcBWNmubGZ-U',
    appId: '1:773794068767:web:497468f290335effbf582a',
    messagingSenderId: '773794068767',
    projectId: 'proyectoapianime',
    authDomain: 'proyectoapianime.firebaseapp.com',
    storageBucket: 'proyectoapianime.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0HUT914BObUFjwNAQn5Ta3myBpz_eiCc',
    appId: '1:773794068767:android:2c3beee42dd52cdabf582a',
    messagingSenderId: '773794068767',
    projectId: 'proyectoapianime',
    storageBucket: 'proyectoapianime.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfe-kTaOB7Sj4CShZawNSvFsLmiJgQwaQ',
    appId: '1:773794068767:ios:b959eb518e81703bbf582a',
    messagingSenderId: '773794068767',
    projectId: 'proyectoapianime',
    storageBucket: 'proyectoapianime.appspot.com',
    iosBundleId: 'com.example.animeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfe-kTaOB7Sj4CShZawNSvFsLmiJgQwaQ',
    appId: '1:773794068767:ios:dfa55bedcf87789abf582a',
    messagingSenderId: '773794068767',
    projectId: 'proyectoapianime',
    storageBucket: 'proyectoapianime.appspot.com',
    iosBundleId: 'com.example.animeApp.RunnerTests',
  );
}
